# Site settings
title: Social Data Science
#email: sebastian.barfort@econ.ku.dk
description: Fall 2015<br/> Department of Economics<br/> University of Copenhagen
baseurl: "" 
url:  "http://sebastianbarfort.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  sebastianbarfort/dsss

# Build settings
markdown: kramdown
